import { LegalDocument, type LegalSection } from "@/components/legal/LegalDocument";

export const metadata = {
  title: "Privacy Policy — i-FAB",
  description:
    "How the International Foot and Ankle Biomechanics Community collects, uses, and protects personal data submitted through this website.",
  // Draft: keep out of search results until the content is signed off.
  robots: { index: false, follow: false },
};

/**
 * Factual sections mirror what the site actually does today:
 * `app/api/join/route.ts` and `app/api/contact-board/route.ts` email the form
 * fields to the board via Resend and store nothing. Anything that is an
 * organisational or legal decision is left as a `[[TO CONFIRM: …]]` placeholder.
 */
const SECTIONS: LegalSection[] = [
  {
    heading: "Who we are",
    body: [
      "The International Foot and Ankle Biomechanics Community (i-FAB) operates this website and is the data controller for the personal data described below.",
      "Controller details: [[TO CONFIRM: registered name, legal form, registered address, and registration number of the i-FAB entity acting as controller]].",
      "Data protection contact: [[TO CONFIRM: whether a Data Protection Officer or a named contact is appointed, and the address for privacy enquiries — info@i-fab.org is used elsewhere on this site]].",
    ],
  },
  {
    heading: "What personal data we collect",
    body: [
      "We only collect personal data that you submit to us directly through one of the two forms on this site. We do not require an account, and we do not buy or otherwise acquire personal data from third parties.",
      "Through the Join i-FAB form we collect: full name, email address, employer, city, country, main role, research line, and anything you choose to write in the free-text message box. Only the name, email address and main role are required. These submissions are stored as records in our content management system, together with the date and time of submission, so that the board can review them.",
      "Because the message box is free text, please include only what you want the board to have. Do not send sensitive information such as health data through it.",
      "Our web host and content delivery network process technical data such as IP address and browser user agent in order to serve the site and to apply basic abuse protection. [[TO CONFIRM: name the hosting provider and whether its server logs are retained, and for how long]].",
    ],
  },
  {
    heading: "How we use your data, and our legal basis",
    body: [
      "Submissions are delivered by email to the i-FAB board so that we can respond to you and consider your interest in the community, and are additionally saved to our content management system so the board can review them together. The content of your submission is not published on this website.",
      "Legal basis: [[TO CONFIRM: whether i-FAB relies on consent (Art. 6(1)(a) GDPR) or legitimate interests (Art. 6(1)(f)) for handling these submissions — and, if legitimate interests, record the balancing assessment. This should be settled together with the question of who the controller is.]].",
      "i-FAB intends to use the email addresses given here to send occasional community communications, such as congress announcements. That is a separate purpose from answering you individually, and it requires your consent.",
      "[[TO CONFIRM: the form does not yet ask for that consent and the emails carry no unsubscribe link, so no address collected so far may be used for communications. Both need to be built before this paragraph becomes true, and addresses gathered before then cannot be brought in retroactively.]]",
    ],
  },
  {
    heading: "Cookies and analytics",
    body: [
      "This website does not set advertising or analytics cookies, and it does not embed third-party tracking scripts.",
      "[[TO CONFIRM: confirm this remains accurate at the time of publication, and update this section if any analytics, embedded media, or marketing tooling is added later — adding such tooling generally requires a consent banner.]]",
    ],
  },
  {
    heading: "Who we share your data with",
    body: [
      "We do not sell your personal data. We share it only with service providers that process it on our behalf, under contract and on our instructions:",
    ],
    bullets: [
      "Resend — delivers the notification emails generated by the two forms. Your submitted details appear in the body of those emails.",
      "Sanity — our content management system. As well as hosting the editorial content of this site, it stores the submissions received through the Join i-FAB form so that the board can review them.",
      "Google — notification emails are delivered to mailboxes held with Gmail, where the board reads and retains them.",
      "[[TO CONFIRM: the hosting provider, and any other processor such as an email inbox provider where the board receives and stores these messages]].",
      "We may also disclose personal data where required to do so by law.",
    ],
  },
  {
    heading: "International transfers",
    body: [
      "Some of the providers above process data outside the country in which you are located, including in the United States.",
      "[[TO CONFIRM: identify the transfer mechanism relied on for each processor — for example Standard Contractual Clauses or an adequacy decision — and record the corresponding documentation]].",
    ],
  },
  {
    heading: "How long we keep your data",
    body: [
      "Submissions are stored as records in our content management system (Sanity) and are also present in the notification email sent to the board, which remains in the inbox that receives it.",
      "A separate Contact the Board form was previously offered on the Scientific Board page. It has been withdrawn, but messages sent through it while it was available may still be held in that inbox.",
      "We keep submissions for four years from the date they are made. That period spans two congress cycles, which is how long a submission stays useful for the purpose it was given for. After it, the record is deleted from the content management system and the corresponding notification email is deleted from the inbox.",
      "[[TO CONFIRM: who on the board is responsible for carrying out these deletions, and when the first review falls due. The period above is only meaningful if someone actually applies it — nothing deletes automatically today.]]",
    ],
  },
  {
    heading: "Your rights",
    body: [
      "If you are in the United Kingdom, the European Economic Area, or another jurisdiction with comparable legislation, you have the right to:",
    ],
    bullets: [
      "request access to the personal data we hold about you;",
      "request that inaccurate data be corrected;",
      "request erasure of your data;",
      "request that we restrict processing, or object to it;",
      "request a copy of your data in a portable format;",
      "withdraw consent at any time, where we rely on consent; and",
      "lodge a complaint with a supervisory authority. [[TO CONFIRM: name the lead supervisory authority for the i-FAB entity and give its contact details]].",
    ],
  },
  {
    heading: "Security",
    body: [
      "The site is served over HTTPS with a strict transport security policy, sets a content security policy, and applies rate limiting to its form endpoints.",
      "No method of transmission or storage is completely secure, and we cannot guarantee absolute security. Please do not send sensitive personal information — such as health data — through these forms.",
    ],
  },
  {
    heading: "Changes to this policy",
    body: [
      "We may update this policy from time to time. The date at the top of this page shows when it was last revised.",
    ],
  },
  {
    heading: "Contact us",
    body: [
      "For any question about this policy or to exercise any of the rights above, contact us at info@i-fab.org. [[TO CONFIRM: whether privacy requests should go to a dedicated address instead]].",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <LegalDocument
      draft
      title="Privacy Policy"
      lastUpdated="[[TO CONFIRM: publication date]]"
      intro="This policy explains what personal data the i-FAB website collects, why we collect it, who it is shared with, and the rights you have over it."
      sections={SECTIONS}
    />
  );
}
