/**
 * Slides para `PublicImageCarousel`.
 * Congresso: `public/congress/` (image1 … image71). About: `public/about/` (image1 … image8).
 */
export type PublicCarouselSlide = {
  src: string;
  alt: string;
};

/** Imagens do carrossel na página Conferences (`/public/congress/`). */
export const CONGRESS_CAROUSEL_SLIDES: PublicCarouselSlide[] = [
  { src: "/congress/image1.jpg", alt: "iFAB meeting" },
  { src: "/congress/image2.jpg", alt: "iFAB meeting" },
  { src: "/congress/image3.jpg", alt: "iFAB meeting" },
  { src: "/congress/image4.jpg", alt: "iFAB meeting" },
  { src: "/congress/image5.jpg", alt: "iFAB meeting" },
  { src: "/congress/image6.jpg", alt: "iFAB meeting" },
  { src: "/congress/image7.jpg", alt: "iFAB meeting" },
  { src: "/congress/image8.jpg", alt: "iFAB meeting" },
  { src: "/congress/image9.jpg", alt: "iFAB meeting" },
  { src: "/congress/image10.jpg", alt: "iFAB meeting" },
  { src: "/congress/image11.jpg", alt: "iFAB meeting" },
  { src: "/congress/image12.jpg", alt: "iFAB meeting" },
  { src: "/congress/image13.jpg", alt: "iFAB meeting" },
  { src: "/congress/image14.jpg", alt: "iFAB meeting" },
  { src: "/congress/image15.jpg", alt: "iFAB meeting" },
  { src: "/congress/image16.jpg", alt: "iFAB meeting" },
  { src: "/congress/image17.JPG", alt: "iFAB meeting" },
  { src: "/congress/image18.bmp", alt: "iFAB meeting" },
  { src: "/congress/image19.jpg", alt: "iFAB meeting" },
  { src: "/congress/image20.jpg", alt: "iFAB meeting" },
  { src: "/congress/image21.jpg", alt: "iFAB meeting" },
  { src: "/congress/image22.jpg", alt: "iFAB meeting" },
  { src: "/congress/image23.jpg", alt: "iFAB meeting" },
  { src: "/congress/image24.jpg", alt: "iFAB meeting" },
  { src: "/congress/image25.jpg", alt: "iFAB meeting" },
  { src: "/congress/image26.jpg", alt: "iFAB meeting" },
  { src: "/congress/image27.jpg", alt: "iFAB meeting" },
  { src: "/congress/image28.jpg", alt: "iFAB meeting" },
  { src: "/congress/image29.jpg", alt: "iFAB meeting" },
  { src: "/congress/image30.jpg", alt: "iFAB meeting" },
  { src: "/congress/image31.jpg", alt: "iFAB meeting" },
  { src: "/congress/image32.jpg", alt: "iFAB meeting" },
  { src: "/congress/image33.jpg", alt: "iFAB meeting" },
  { src: "/congress/image34.jpg", alt: "iFAB meeting" },
  { src: "/congress/image35.jpg", alt: "iFAB meeting" },
  { src: "/congress/image36.jpg", alt: "iFAB meeting" },
  { src: "/congress/image37.jpg", alt: "iFAB meeting" },
  { src: "/congress/image38.jpg", alt: "iFAB meeting" },
  { src: "/congress/image39.jpg", alt: "iFAB meeting" },
  { src: "/congress/image40.jpg", alt: "iFAB meeting" },
  { src: "/congress/image41.jpg", alt: "iFAB meeting" },
  { src: "/congress/image42.JPG", alt: "iFAB meeting" },
  { src: "/congress/image43.JPG", alt: "iFAB meeting" },
  { src: "/congress/image44.JPG", alt: "iFAB meeting" },
  { src: "/congress/image45.JPG", alt: "iFAB meeting" },
  { src: "/congress/image46.JPG", alt: "iFAB meeting" },
  { src: "/congress/image47.JPG", alt: "iFAB meeting" },
  { src: "/congress/image48.JPG", alt: "iFAB meeting" },
  { src: "/congress/image49.JPG", alt: "iFAB meeting" },
  { src: "/congress/image50.JPG", alt: "iFAB meeting" },
  { src: "/congress/image51.JPG", alt: "iFAB meeting" },
  { src: "/congress/image52.JPG", alt: "iFAB meeting" },
  { src: "/congress/image53.JPG", alt: "iFAB meeting" },
  { src: "/congress/image54.JPG", alt: "iFAB meeting" },
  { src: "/congress/image55.JPG", alt: "iFAB meeting" },
  { src: "/congress/image56.JPG", alt: "iFAB meeting" },
  { src: "/congress/image57.png", alt: "iFAB meeting" },
  { src: "/congress/image58.jpeg", alt: "iFAB meeting" },
  { src: "/congress/image59.jpg", alt: "iFAB meeting" },
  { src: "/congress/image60.jpg", alt: "iFAB meeting" },
  { src: "/congress/image61.jpg", alt: "iFAB meeting" },
  { src: "/congress/image62.jpg", alt: "iFAB meeting" },
  { src: "/congress/image63.jpeg", alt: "iFAB meeting" },
  { src: "/congress/image64.jpg", alt: "iFAB meeting" },
  { src: "/congress/image65.jpg", alt: "iFAB meeting" },
  { src: "/congress/image66.jpg", alt: "iFAB meeting" },
  { src: "/congress/image67.jpg", alt: "iFAB meeting" },
  { src: "/congress/image68.jpg", alt: "iFAB meeting" },
  { src: "/congress/image69.jpg", alt: "iFAB meeting" },
  { src: "/congress/image70.png", alt: "iFAB meeting" },
  { src: "/congress/image71.png", alt: "iFAB meeting" },
];

/** Imagens do carrossel em About Us / Mission (`/public/about/` — image1 … image8). */
export const ABOUT_CAROUSEL_SLIDES: PublicCarouselSlide[] = [
  { src: "/about/image2.png", alt: "iFAB mission" },
  { src: "/about/image6.jpg", alt: "iFAB mission" },
  { src: "/about/image3.png", alt: "iFAB mission" },
  { src: "/about/image7.jpg", alt: "iFAB mission" },
  { src: "/about/image4.jpg", alt: "iFAB mission" },
  { src: "/about/image1.png", alt: "iFAB mission" },
  { src: "/about/image5.jpg", alt: "iFAB mission" },
  { src: "/about/image8.png", alt: "iFAB mission" },
];
